// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemperSounds.Core.Data;

#nullable disable

namespace SemperSounds.Core.Data.Migrations
{
    [DbContext(typeof(SoundboardDbContext))]
    [Migration("20260813204130_AddActivityLogPlayStatsIndex")]
    partial class AddActivityLogPlayStatsIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SemperSounds.Core.Data.ActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SoundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Kind", "SoundId", "OccurredAt");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.EntrySound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SoundId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoundId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EntrySounds");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.EntrySoundBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EntrySoundBlocks");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.EntrySoundSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerUserCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SnoozedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumePercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EntrySoundSettings", t =>
                        {
                            t.HasCheckConstraint("CK_EntrySoundSettings_Singleton", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            MaxDurationMs = 5000,
                            PerUserCooldownSeconds = 60,
                            UpdatedAt = 639028224000000000L,
                            VolumePercent = 70
                        });
                });

            modelBuilder.Entity("SemperSounds.Core.Data.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SoundId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoundId");

                    b.HasIndex("UserId", "Slot")
                        .IsUnique();

                    b.HasIndex("UserId", "SoundId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.Sound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("🙂");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UploadedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploaderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.EntrySound", b =>
                {
                    b.HasOne("SemperSounds.Core.Data.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sound");
                });

            modelBuilder.Entity("SemperSounds.Core.Data.Favorite", b =>
                {
                    b.HasOne("SemperSounds.Core.Data.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sound");
                });
#pragma warning restore 612, 618
        }
    }
}
